class AppError extends Error {
  constructor(message, statusCode, errorCode) {
    super(message);
    this.statusCode = statusCode;
    this.errorCode = errorCode;
    this.isOperational = true;
         
    Error.captureStackTrace(this, this.constructor);
  }
}

// Codes d'erreur standards
const ErrorCodes = {
  // ===== VALIDATION ERRORS =====
  VALIDATION_ERROR: 'VALIDATION_ERROR',
  VALIDATION_PASSWORD_WEAK: 'VALIDATION_PASSWORD_WEAK',
  VALIDATION_EMAIL_INVALID: 'VALIDATION_EMAIL_INVALID',
  
  // ===== AUTHENTICATION ERRORS =====
  AUTH_TOKEN_MISSING: 'AUTH_TOKEN_MISSING',
  AUTH_INVALID_TOKEN: 'AUTH_INVALID_TOKEN',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_USER_NOT_FOUND: 'AUTH_USER_NOT_FOUND',
  AUTH_ACCOUNT_DISABLED: 'AUTH_ACCOUNT_DISABLED',
  AUTH_EMAIL_EXISTS: 'AUTH_EMAIL_EXISTS',
  AUTH_PHONE_EXISTS: 'AUTH_PHONE_EXISTS',
  AUTH_CODE_EXISTS: 'AUTH_CODE_EXISTS',
  
  // ===== BUSINESS ERRORS =====
  SUBSCRIPTION_REQUIRED: 'SUBSCRIPTION_REQUIRED',
  PACKAGE_NOT_AVAILABLE: 'PACKAGE_NOT_AVAILABLE',
  CATEGORY_ACCESS_DENIED: 'CATEGORY_ACCESS_DENIED',
  AFFILIATE_CODE_INVALID: 'AFFILIATE_CODE_INVALID',
  COMMISSION_NOT_FOUND: 'COMMISSION_NOT_FOUND',
  PAYMENT_REQUIRED: 'PAYMENT_REQUIRED',
  
  // ===== RESOURCE ERRORS =====
  NOT_FOUND: 'NOT_FOUND',
  ALREADY_EXISTS: 'ALREADY_EXISTS',
  RESOURCE_LOCKED: 'RESOURCE_LOCKED',
  RESOURCE_EXPIRED: 'RESOURCE_EXPIRED',
  
  // ===== PERMISSION ERRORS =====
  FORBIDDEN: 'FORBIDDEN',
  INSUFFICIENT_PERMISSIONS: 'INSUFFICIENT_PERMISSIONS',
  OWNERSHIP_REQUIRED: 'OWNERSHIP_REQUIRED',
  
  // ===== OPERATION ERRORS =====
  OPERATION_FAILED: 'OPERATION_FAILED',
  OPERATION_NOT_ALLOWED: 'OPERATION_NOT_ALLOWED',
  DUPLICATE_OPERATION: 'DUPLICATE_OPERATION',
  
  // ===== GENERAL ERRORS =====
  BAD_REQUEST: 'BAD_REQUEST',
  INTERNAL_ERROR: 'INTERNAL_ERROR',
  RATE_LIMIT_EXCEEDED: 'RATE_LIMIT_EXCEEDED',
  SERVICE_UNAVAILABLE: 'SERVICE_UNAVAILABLE'
};

module.exports = { AppError, ErrorCodes };